### ISSUE TITLE
Unable to start profiler

### ISSUE THREAD

**Issue by raszi** [clojure-goes-fast/clj-async-profiler#32]
First of all, thank you for the great tool!

Unfortunately, I am having issues starting the profiler using Docker images:
- `eclipse-temurin:17-jre-ubi9-minimal`
- `eclipse-temurin:19-jre-ubi9-minimal`
- `eclipse-temurin:21-jre-ubi9-minimal`

First I got:

```
java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @6ab1d6ac
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(Unknown Source)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.Method.setAccessible(Unknown Source)
        at clj_async_profiler.core$add_url_to_classloader_reflective.invokeStatic(core.clj:54)
        at clj_async_profiler.core$fn__15318.invokeStatic(core.clj:87)
        at clj_async_profiler.core$fn__15318.invoke(core.clj:82)
        at clojure.lang.Delay.deref(Delay.java:42)
        at clojure.core$deref.invokeStatic(core.clj:2337)
        at clj_async_profiler.core$get_virtualmachine_class.invokeStatic(core.clj:93)
        at clj_async_profiler.core$mk_vm.invokeStatic(core.clj:192)
        at clj_async_profiler.core$attach_agent.invokeStatic(core.clj:210)
        at clj_async_profiler.core$start.invokeStatic(core.clj:268)
 ```

When I add JVM arg: `--add-opens=java.base/java.net=ALL-UNNAMED`, then I receive the following:

```
java.lang.IllegalArgumentException: object is not an instance of declaring class
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at clj_async_profiler.core$add_url_to_classloader_reflective.invokeStatic(core.clj:55)
        at clj_async_profiler.core$fn__15318.invokeStatic(core.clj:87)
        at clj_async_profiler.core$fn__15318.invoke(core.clj:82)
        at clojure.lang.Delay.deref(Delay.java:42)
        at clojure.core$deref.invokeStatic(core.clj:2337)
        at clj_async_profiler.core$get_virtualmachine_class.invokeStatic(core.clj:93)
        at clj_async_profiler.core$mk_vm.invokeStatic(core.clj:192)
        at clj_async_profiler.core$attach_agent.invokeStatic(core.clj:210)
        at clj_async_profiler.core$start.invokeStatic(core.clj:268)
```

Is there any trick that I missed? :)

**Comment by raszi** [comment]
I found the problem, we need the JDK JRE is not enough.

**Comment by alexander-yakushev** [comment]
Glad you've resolved it. I should mention that the profiler requires JDK in the README.
